### ISSUE TITLE
Nullable bools set to false instead of being left null

### ISSUE THREAD

**Issue by davidbending** [chaowlert/Mapster#1]
If I have a source class like this:

```
public class SourceClass
{
  public bool Bool { get; set; }
  public bool ShouldMap { get; set; }
}
```

and a destination like this:

```
 public class DestClass
 {
  public bool? NullableBool { get; set; }
 }
```

and a mapping like this:

```
  TypeAdapterConfig.GlobalSettings.Clear();
  TypeAdapterConfig.GlobalSettings.NewConfig<SourceClass, DestClass>()
    .IgnoreNullValues(true)
    .Map(dst => dst.NullableBool, src => src.Bool, src => src.ShouldMap)
    .Compile();
```
I would expect NullableBool to be null after mapping, but it's actually false.

**Comment by chaowlert** [comment]
`Map` method will always set value to destination. If no condition met, it will return default value (in this case `false`). You can fix it by casting source value to nullable (to make default value equals to null). (https://github.com/chaowlert/Mapster/wiki/Custom-mapping#mapping-with-condition)

    .Map(dst => dst.NullableBool, src => (bool?)src.Bool, src => src.ShouldMap)

There is another method called `IgnoreIf`, if you would like to skip mapping.

    .Map(dst => dst.NullableBool, src => src.Bool)
    .IgnoreIf((src, dst) => !src.ShouldMap, dst => dst.NullableBool)

NOTE: `IgnoreNullValues` doesn't help, it is for ignore mapping is source value is null.
