### ISSUE TITLE
Mapping for all derived types

### ISSUE THREAD

**Issue by Laban1** [chaowlert/Mapster#10]
Hi,

I have a couple of base classes, ModelBase and ModelVmBase.  There are 50+ classes inheriting from each.  

Here is the ModelBase (used by the EF objects).  It has two nested User properties:

```
public class ModelBase 
{
	public virtual User CreatedByUser { get; set; } // The nested User object has a UserName property
	public virtual User UpdatedByUser { get; set; } // The nested User object has a UserName property
}

```

Here is the ModelVmBase, which is the base class for the DTOs / VMs:
```
public class ModelVmBase 
{
	public string CreatedByUserName { get; set; }
	public string UpdatedByUserName { get; set; }
}
```
What I am trying to do is to map the nested UserName of the ModelBase to the corresponding UserName property in the ModelVmBase.  

I know that I can do accomplish this with a specific mapping for each of the sub-classes, e.g.:
```
TypeAdapterConfig<Note, NoteVm>
	.NewConfig()
	.Map(dest => dest.UpdatedByUserName, src => src.UpdatedByUser.UserName)
	.Map(dest => dest.CreatedByUserName, src => src.CreatedByUser.UserName);
```

However, with 50+ inheriting classes, it would be much cleaner if I could just define this for the ModelBase and ModelVmBase:

```
TypeAdapterConfig<ModelBase, ModelVmBase>
	.NewConfig()
	.Map(dest => dest.UpdatedByUserName, src => src.UpdatedByUser.UserName)
	.Map(dest => dest.CreatedByUserName, src => src.CreatedByUser.UserName);

```

However, it does not work when doing it on the base classes (=the CreatedByUserName and UpdatedByUserName are not getting mapped).  Is there a way to make this work w/o doing it for each subclass?

Thanks.

**Comment by chaowlert** [comment]
You can set `TypeAdapterConfig.GlobalSettings.AllowImplicitDestinationInheritance = true;` if you would like to apply mapping to all derived types. (see more https://github.com/chaowlert/Mapster/wiki/Config-inheritance)

**Comment by Laban1** [comment]
@chaowlert Thanks - that solved that particular issue.  However, I now get null reference exceptions on mappings that were working before, e.g. in an EF object which has a lot of nested objects (navigation properties).  

For performance reasons I do not include every one of the nested objects, so some of them are null; I assume this this is what causes the null reference exception.  

I have tried setting TypeAdapterConfig.GlobalSettings.Default.IgnoreNullValues(true), but that did not help.  Again, the issue only occurs when I have AllowImplicitDestinationInheritance (true).

Any ideas?

**Comment by chaowlert** [comment]
For debugging, pls use `Mapster.Diagnostics` (https://github.com/chaowlert/Mapster/wiki/Debugging). It will show you real problem.

My feeling is it is not about nav prop. Mapster should not break because there is null value. It might be some datatype that Mapster doesn't support (for example `DbGeography`). In this case, you need to create your own mapping. `TypeAdapterConfig<TypeA, TypeB>.NewConfig().MapWith(...)`

**Comment by Laban1** [comment]
@chaowlert  

Ok, I have used the diagnostic package and the exception is happening here in file C:\Windows\Microsoft.NET\Framework\v4.0.30319\Temporary ASP.NET Files\root\9d99fecb\fec77759\assembly\dl3\69089e4d\00627ff9_f5d7d201\Mapster\Address-AddressVm.cs:
![image](https://user-images.githubusercontent.com/9595654/30255761-c2b08eec-965a-11e7-9546-2071fda41e16.png)

It is the CreatedByUser property of the Address object that is null.  

The Company object includes a number of Address properties and each Address object has a few AimmUser properties, for example CreatedByUser:
```
Company
{
   public virtual Address PhysicalAddress { get; set; }
}

Address
{
   AimmUser CreatedByUser { get; set; }
}

AimmUser
{
   string AimmUserName  { get; set; }
}
```

In this case it appears that mapster handles first-level null properties fine, but not deeper than that, so when the CreatedByUser property (as in company.PhysicalAddress.**CreatedByUser**.AimmUserName) is null it throws a null reference exception when trying to get to its  AimmUserName property.  
 
Please advise.

**Comment by chaowlert** [comment]
Isn't that because of your mapping code? Change your mapping code to

```
TypeAdapterConfig<ModelBase, ModelVmBase>
	.NewConfig()
	.Map(dest => dest.UpdatedByUserName, src => src.UpdatedByUser == null ? null : src.UpdatedByUser.UserName)
	.Map(dest => dest.CreatedByUserName, src =>  src.UpdatedByUser == null ? null : src.CreatedByUser.UserName);
```

**Comment by Laban1** [comment]
@chaowlert You are absolutely correct - it works fine now.
