### ISSUE TITLE
String to Enum

### ISSUE THREAD

**Issue by coleary01** [chaowlert/Mapster#11]
Just updated to 3.1.4 from 2.6.0

Keep getting:

System.InvalidCastException: 'Invalid cast from 'System.String' to 'TKG.Atlanta.Common.Types.RoadTypes'.'

On the auto mapper from my Infrastructure layer to my DTO. I dont have any config files in between.

This was working before I upgraded. Any thoughts?

**Comment by chaowlert** [comment]
It should be fine. Could you provide `RoadTypes` enum declaration code, source string and if you have mapping configuration related to this conversion pls also provide.

**Comment by coleary01** [comment]
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace TKG.Atlanta.Common.Types
{
    /// <summary>
    /// The road types.
    /// </summary>
    public enum RoadTypes
    {
        Type0,
        Type1,
        Type2,
        Type3,
        Type4,
        Footpath,
        Verge,
        Unknown
    }
}

The strings are in the database stored as below:

[roadtype]
Type3
Type2

No config as using the auto mapping facility. As mentioned this was working prior to updating.

**Comment by coleary01** [comment]
I think ive resolved the issue.

The error occurred while trying to load a JobActivity from the database to a DTO.

The activity used the enum as: 

public RoadType? RoadType 

This was nullable because if the property "Highway" was set to private then this propery wasnt required.

If removed RoadType as nullable and added a "NA" option.

This is now working fine.

Still doesnt explain how this worked in previous versions.

**Comment by chaowlert** [comment]
Thx u, the info is good enough. I think we miss unit case for casting between string and nullable enum.
