### ISSUE TITLE
How to use framework specific services during mapping

### ISSUE THREAD

**Issue by freudj76** [chaowlert/Mapster#2]
Let's say I have a model class called UserModel such as

    public class UserModel
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public string EditUrl { get; set; }
    }

My mapping config is

    public class MappingConfig : IRegister    
    {
            public void Register(TypeAdapterConfig config)
            {
                config.NewConfig<User, UserModel>()
                .Map(dest => dest.Id, src => src.Id)
                .Map(dest => dest.Name, src => $"{src.FirstName} {src.LastName}");
            }
    }
 
This config is scanned during app startup. (This is a .net core project)

`TypeAdapterConfig.GlobalSettings.Scan(typeof(Startup).GetTypeInfo().Assembly);`

And finally, in one of the services, the actual mapping happens by projection as follows;

`Users = await query.Take(Count).ProjectToType<UserModel>().ToListAsync();`

One thing I would like to accomplish is to also compute the EditUrl in my model class. This would require passing in a UrlHelper, which is actually within the HttpContext.

My question is, is this even possible? Configuration is scanned and then compiled once during startup, then how can it make use of a context class that changes with each request? i tried to pass the HttpContext by using MappingContext parameter, that didnt work for me. 

I will be OK if I need to give up config scanning at the app startup if there is a way of passing config during mapping without causing a recompile or perf hit.

Thanks for the help, super awesome library.

**Comment by chaowlert** [comment]
`HttpContext` is static, you can map directly.

    TypeAdapterConfig<User, UserModel>.NewConfig()
        .Map(dst => dst.EditUrl, src => HttpContext.Current.Whatever);

`MapContext` should also work in your case, but better use `HttpContext` because it already contains the value.

**Comment by freudj76** [comment]
Thanks for the reply. HttpContext.Current doesnt exist in asp.net core. Only way to get access to an HttpContext is to inject an IHttpContextAccessor using core's DI, however, I can't have an implementation of IRegister with a constructor that requires params. I will re-try MappingContext, but maybe I should rephrase the question as "Is there anyway of hooking into asp.net core's DependencyInjection"?

**Comment by chaowlert** [comment]
There is no way for `Scan` method to perform injection. You can instantiate `IRegister` using DI first, and then pass to `config.Apply`.

**Comment by freudj76** [comment]
Ok, I gave it a try. At least it is working. I do have a performance question.
My DI is instantiating IRegister per request and injecting HttpContext (if it is not per request, I wouldnt get the current request context)
So with each request, there is a new IRegister instance, then a call to config.apply.
Doesnt this cause a perf hit because config needs to be recompiled?
Or maybe I am doing it wrong? Dont I need to create a new TypeAdapterConfig with each request, otherwise, how do I pass the current context (any runtime value that might change from request to request) to the config in effect?

**Comment by chaowlert** [comment]
The scenario is quite complicated. Let's use `MapContext` then. In your setup class:

    TypeAdapterConfig<User, UserModel>.NewConfig()
        .Map(dst => dst.EditUrl, src => (string)MapContext.Current.Properties["EditUrl"]);

When mapping

    using (var scope = new MapContextScope())
    {
        var parameters = scope.Context.
        parameters["EditUrl"] = httpContext.Whatever;
        Users = await query.Take(Count).ProjectToType<UserModel>().ToListAsync();
    }

If above code doesn't work, pls try using `ToList` instead of `ToListAsync`. `MapContext` is thread local not async local. I will add support for async local at some point.

**Comment by freudj76** [comment]
Thank you, you have been super helpful
