### ISSUE TITLE
Really impressive

### ISSUE THREAD

**Issue by eric-swann-q2** [chaowlert/Mapster#3]
Thanks for taking over this project and really taking it to the next level.  3.0 looks amazing!

**Comment by chaowlert** [comment]
Thank you Eric, your code base is good foundation. I also need to thank you, I used Mapster quite a long time for several projects, that's why I would love to maintain it.

**Comment by j-hogue** [comment]
Flawless upgrade from 2.6.1 -> 3.1.0.  I did not have to change anything to use 3.1.0. I did add `TypeAdapterConfig.GlobalSettings.Default.AvoidInlineMapping(true);` to increase mapping speed of large nested pocos. So far no issues... Thank you @chaowlert for taking this project on, please keep up the great work.
