### ISSUE TITLE
Multiple ShouldMap conditions appear in the wrong side of the Ternary operator

### ISSUE THREAD

**Issue by Slicksim** [chaowlert/Mapster#4]
When adding multiple conditions to a property, they are nested within the true block of the ternary operator in the outputted lambda.  

This prevents multiple conditions from applying correctly, as each previous condition would need to evaluate to true to enable it to work.

E.g.

```
.Map(m => m.MonthOption, m => ((int)PayCycleDay.SpecificDay).ToString(), m => m.PayCycle == "M" && m.DayOfMonth != 0)
.Map(m => m.MonthOption, m => ((int)PayCycleDay.Last).ToString(), m => m.FromLast)
.Map(m => m.MonthOption, m => ((int)PayCycleDay.First).ToString(), m => m.IntervalFrom == 1)
.Map(m => m.MonthOption, m => ((int)PayCycleDay.Second).ToString(), m => m.IntervalFrom == 2)
.Map(m => m.MonthOption, m => ((int)PayCycleDay.Third).ToString(), m => m.IntervalFrom == 3)
.Map(m => m.MonthOption, m => ((int)PayCycleDay.Fourth).ToString(), m => m.IntervalFrom == 4)
```

This produced the following ternary condition in the Mapster.Diagnostics:
```
(int)p1.IntervalFrom == 4 ? 
	((int)p1.IntervalFrom == 3 ? 
		((int)p1.IntervalFrom == 2 ? 
			((int)p1.IntervalFrom == 1 ? 
				(p1.FromLast ? 
					(p1.PayCycle == "M" && (int)p1.DayOfMonth != 0 ? 100.ToString() : 600.ToString()) 
				: 200.ToString()) 
			: 300.ToString()) 
		: 400.ToString()) 
	: 500.ToString()) 
: null
```

**Comment by chaowlert** [comment]
thx for reporting, I will fix soon

**Comment by chaowlert** [comment]
I just upload 3.1.1 but still unlisted for testing. Could you please try with new version and test whether this version work correctly?

    Install-Package Mapster -Version 3.1.1

**Comment by Slicksim** [comment]
Thanks @chaowlert , that is now generating the correct ternary condition as expected.  Many thanks for such a quick response.
