### ISSUE TITLE
enum mapping

### ISSUE THREAD

**Issue by gbjbaanb** [chaowlert/Mapster#5]
Great project, very happy about the performance - much underestimated nowadays.

I'm trying to map a ASP.NET multiple-select control to an flags enum. I can get the select control to populate a List<string>, but I can't seem to get any way of mapping that to the enum. It works perfectly with a single string and normal enum type, but flags seem to give it a bit of grief. 

Am I just inexperienced with Mapster, or is this not (yet?) possible?

**Comment by chaowlert** [comment]
Mapster doesn't support mapping list of string to flags enum. There are 2 ways to do this.

1. Change list of string to comma separated string. For example:

```
var e = "Read, Write, Delete".Adapt<FileShare>();  
//FileShare.Read | FileShare.Write | FileShare.Delete
```

2. Create your own logic using `MapWith`

```
//somewhere in startup
TypeAdapterConfig<List<string>, FileShare>.NewConfig().MapWith(src => YourOwnLogic(src));

//or you can let Mapster do the logic
//TypeAdapterConfig<List<string>, FileShare>.NewConfig().MapWith(src => string.Join(",", src).Adapt<FileShare>());
```

**Comment by gbjbaanb** [comment]
I did this in the end:

```
var resultenum = mylist.Select(x => { myenum outenum; Enum.TryParse(x, out outenum); return outenum; }).Aggregate((prev, next) => prev | next);
```

this turns the list of strings into the flag enum.
and 

```
mylist = myenum.ToString().Split(',').Select(s => s.Trim()).ToList();
```

turns the enum into a list of strings.
