### ISSUE TITLE
mapping to an existing object

### ISSUE THREAD

**Issue by jayheavner** [chaowlert/Mapster#6]
I have multiple objects I'm trying to merge into one. I had assumed the following would work:

```
var result = type1Data.Adapt<List<Type1>, List<TypeNeeded>>();
result = type2Data.Adapt(result);

```
But I'm left with an object that only has type2Data. How do I combine different types into an existing object?

**Comment by jayheavner** [comment]
If I'm trying to combine two lists together, how do I specify the identify to match? If I break it out into a loop and find the item from the second collection then it works.

**Comment by chaowlert** [comment]
Mapping existing list to existing list and identifying the matching are not supported. Breaking out and find individual item then make the mapping is the way to go.

Could you please tell me more about what you intend to do?

**Comment by jayheavner** [comment]
Yeah, I realized what I was asking was impossible, there's no way two lists could be mapped without key(s). Right now I'm using a loop to get what I need but I'll probably make an extension method that takes the types and a key to join that joins the data.

Right now I'm working with a CMS that returns flat data data with methods to traverse but it needs to be converted into nested models that represent the tree structure. The methods for traversing hit the DB and that doesn't scale.
