### ISSUE TITLE
How to Map Iqueryable objects

### ISSUE THREAD

**Issue by AbhinavSharma1987** [chaowlert/Mapster#7]
I have a situation where I need to map Iqueryable of DtoModel to Iqueryable of DomainModel

Is this possible to do so using Mapster?

Thanks,
Abhinav Sharma

**Comment by AbhinavSharma1987** [comment]
Any Suggestion would be appreciable as I need to make decision very soon on whether we should use Mapster package or not.

I found it very cool package and it suffice almost all requirements, however I am stuck with Iqueryable object mapping issue.

Thanks,
Abhinav

**Comment by chaowlert** [comment]
Pls check here https://github.com/chaowlert/Mapster/wiki/Basic-usages#queryable-extensions

**Comment by AbhinavSharma1987** [comment]
Hi Chaowlert,

Thanks for the reference. It helped. :)
I should have checked earlier. but thanks :) much appreciated for your quick response.
