### ISSUE TITLE
Issue with collections and record types

### ISSUE THREAD

**Issue by nickball-granta** [chaowlert/Mapster#9]
I'm getting an error with the following structure:

    internal class ModelDTO
    {
        public string Id { get; set; }
        public string Name { get; set; }
    }
    internal class ParentDTO 
    {
        public List<ModelDTO> Models { get; set; }
    }
    internal class Model 
    {
        public Model(string id)
        {
            Id = id;
            Name = Global.GoOffAndGetName(id);
        }

        public string Id { get; }
        public string Name { get; }
    }

var model= parentDTO.Models.Adapt<List<Model>>();

The error I get is: Cannot convert immutable type, please consider using 'MapWith' method to create mapping. I'm not sure how to use that, or even if it is appropriate. The issue is caused by the Name property in the model; if I add this to the constructor the error goes away. I've tried marking the field as AdaptIgnore, but no joy there. What's the best way to deal with collections in this scenario?

Thanks

**Comment by chaowlert** [comment]
Record type definition for Mapster is quite pure functional style, it doesn't yet support classes with business logic.

For now, you can use `MapWith` as error message suggested.

    TypeAdapterConfig<ModelDto, Model>.NewConfig()
         .MapWith(src => new Model(src.id));

**Comment by nickball-granta** [comment]
Thanks for the help, working now.
